server:
  port: 9200
spring:
  application:
    name: hr
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/hr
    username: root
    password: qpalzm0915
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
