= HR REST API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[Employee-API]]
== Employee API

=== 사원 현재 정보 조회 API

operation::info-list-success[snippets='curl-request,http-request,http-response,response-fields']

=== 특정 사원 현재 정보 조회 API

operation::info-success[snippets='curl-request,http-request,path-parameters,http-response,response-fields']

[[Job-API]]
== Job API

=== 특정 사원 업무 이력 정보 조회 API - no Paging

operation::history-success[snippets='curl-request,http-request,path-parameters,http-response,response-fields']

=== 특정 사원 업무 이력 정보 조회 API - with Paging

operation::history-with-paging-success[snippets='curl-request,http-request,path-parameters,query-parameters,http-response,response-fields']

[[Department-API]]
== Department API

=== 부서 및 위치 정보 조회 API - no Paging

operation::list-success[snippets='curl-request,http-request,http-response,response-fields']

=== 부서 및 위치 정보 조회 API - with Paging

operation::list-with-paging-success[snippets='curl-request,http-request,query-parameters,http-response,response-fields']

=== 부서 및 위치 정보 조회 API - with Paging and Filter

operation::list-with-paging-and-filter-success[snippets='curl-request,http-request,request-fields,http-response,response-fields']

=== 특정 부서 및 해당 업무의 급여 비율 인상 API

operation::update-salary-success[snippets='curl-request,http-request,request-fields,http-response,response-fields']

[[Open-API]]
== Open API

=== 서울특별시 동작구 횡단보도 정보조회 API

operation::cross-walk-open-api-success[snippets='curl-request,http-request,query-parameters,http-response,response-fields']
